name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows you to manually trigger the sync via the UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_repository: ORIGINAL_OWNER/ORIGINAL_REPOSITORY
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
